

//  Question Number Guessing Game:

// This guess the number game is a short TypeScript/Node.js project that allows the user to guess the number generated by the computer. There are also several ways to alter the game, like adding more rounds or displaying the score. It’s quite simple and uses the random function to generate a number.

import * as prompt from 'prompt-sync';

let userGuss: number;
let score = 0;
let rounds = 5;
let attempts = 0;
let min = 1;
let max = 100;
let history: { userGuss: number; attempts: number }[] = [];

function getRandomNumber(): number {
  return Math.floor(Math.random() * (max - min + 1)) + min;
}

function startGame(): void {
  const ask = prompt({ sigint: true });

  console.log(`Hello Welcome to the Guess the Number Game!`);
  console.log(`I am thinking of a number between ${min} and ${max}.`);
  console.log(`Can you guess it whihch number I think?`);

  userGuss = getRandomNumber();
  askQuestion(ask);
}

function askQuestion(ask: prompt.Prompt): void {
  if (rounds === 0) {
    console.log(`  ahh Sorry Game Over! Your score is: ${score}`);
    console.log('Your successful attempts: ', history);

    let answer:string = ask('Do you want to play again game? (y/n) ');
    if (answer.toLowerCase() === 'y') {
      score = 0;
      rounds = 10;
      attempts = 0;
      history = [];
      startGame();
    }
    return;
  }

  let answer:string = ask('Enter a number: ');
  let number = parseInt(answer);

  if (number === userGuss) {
    console.log('Congratulations, you guessed the number!');
    history.push({ userGuss: userGuss, attempts: attempts });
    score++;
    userGuss = getRandomNumber();
    attempts = 0;
  } else {
    attempts++;
    if (attempts % 3 === 0) {
      console.log(`Hint: The userGuss number is ${number < userGuss ? 'greater' : 'less'} than your guess.`);
    } else {
      console.log('Incorrect, try again!');
    }
  }

  rounds--;
  console.log(`You have ${rounds} rounds left.`);
  askQuestion(ask);
}

startGame();











































// wiht OOP

// import * as readline from 'readline';

// interface GameHistory {
//   userGuss: number;
//   attempts: number;
// }

// class GuessGame {
//   private userGuss: number;
//   private score: number;
//   private rounds: number;
//   private attempts: number;
//   private max: number;
//   private min: number;
//   private history: GameHistory[];

//   constructor(min = 1, max = 100, rounds = 10) {
//     this.min = min;
//     this.max = max;
//     this.userGuss = this.getRandomNumber();
//     this.score = 0;
//     this.rounds = rounds;
//     this.attempts = 0;
//     this.history = [];
//   }

//   private getRandomNumber(): number {
//     return Math.floor(Math.random() * (this.max - this.min + 1)) + this.min;
//   }

//   public startGame(): void {
//     const rl = readline.createInterface({
//       input: process.stdin,
//       output: process.stdout
//     });

//     console.log(`Welcome to the Guess the Number Game!`);
//     console.log(`I'm thinking of a number between ${this.min} and ${this.max}.`);
//     console.log(`Can you guess it?`);

//     this.askQuestion(rl);
//   }

//   private askQuestion(rl: readline.Interface): void {
//     if (this.rounds === 0) {
//       console.log(`Game Over! Your score is: ${this.score}`);
//       console.log('Your successful attempts: ', this.history);
//       rl.question('Do you want to play again? (y/n) ', (answer) => {
//         if (answer.toLowerCase() === 'y') {
//           this.score = 0;
//           this.rounds = 10;
//           this.userGuss = this.getRandomNumber();
//           this.attempts = 0;
//           this.startGame();
//         } else {
//           rl.close();
//         }
//       });
//       return;
//     }

//     rl.question('Enter a number: ', (answer) => {
//       const number = parseInt(answer);

//       if (number === this.userGuss) {
//         console.log('Congratulations, you guessed the number!');
//         this.history.push({ userGuss: this.userGuss, attempts: this.attempts });
//         this.score++;
//         this.userGuss = this.getRandomNumber();
//         this.attempts = 0;
//       } else {
//         this.attempts++;
//         if (this.attempts % 3 === 0) {
//           console.log(`Hint: The userGuss number is ${number < this.userGuss ? 'greater' : 'less'} than your guess.`);
//         } else {
//           console.log('Incorrect, try again!');
//         }
//       }

//       this.rounds--;
//       console.log(`You have ${this.rounds} rounds left.`);
//       this.askQuestion(rl);
//     });
//   }
// }

// const game = new GuessGame(1, 100, 10);
// game.startGame();
